.build:
  image: golang:1.21-alpine3.17
  tags:
    - docker
    - walnut
  variables:
    GO_PROJECT: sshabu

stages:
  - building
  # - packaging
  # - deploy

build: 
  stage: building
  extends: .build
  script:
    - GOOS=linux GOARCH=amd64 go build -o $GO_PROJECT-linux-amd64
  artifacts:
    paths:
      - $GO_PROJECT-linux-amd64
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
    # - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+.*$/

